import { OrderData } from "./orders";

export const data: OrderData []= [
  {
    trackingNo: "12i992",
    productName: "Keyboard",
    totalOrder: 10,
    status: "Pending",
    totalAmount: "$1.000.0",
  },
  {
    trackingNo: "12i993",
    productName: "Charge",
    totalOrder: 4,
    status: "Approved",
    totalAmount: "$3.000.0",
  },
  {
    trackingNo: "12i994",
    productName: "Mouse",
    totalOrder: 4,
    status: "Rejected",
    totalAmount: "$500.0",
  },
  {
    trackingNo: "12i995",
    productName: "Screen",
    totalOrder: 4,
    status: "Pending",
    totalAmount: "$2.400.0",
  },
  {
    trackingNo: "12i992",
    productName: "Keyboard",
    totalOrder: 10,
    status: "Pending",
    totalAmount: "$1.000.0",
  },
  {
    trackingNo: "12i993",
    productName: "Charge",
    totalOrder: 4,
    status: "Approved",
    totalAmount: "$3.000.0",
  },
  {
    trackingNo: "12i994",
    productName: "Mouse",
    totalOrder: 4,
    status: "Rejected",
    totalAmount: "$500.0",
  },
  {
    trackingNo: "12i995",
    productName: "Screen",
    totalOrder: 4,
    status: "Pending",
    totalAmount: "$2.400.0",
  },
  {
    trackingNo: "12i992",
    productName: "Keyboard",
    totalOrder: 10,
    status: "Pending",
    totalAmount: "$1.000.0",
  },
  {
    trackingNo: "12i993",
    productName: "Charge",
    totalOrder: 4,
    status: "Approved",
    totalAmount: "$3.000.0",
  },
  {
    trackingNo: "12i994",
    productName: "Mouse",
    totalOrder: 4,
    status: "Rejected",
    totalAmount: "$500.0",
  },
  {
    trackingNo: "12i995",
    productName: "Screen",
    totalOrder: 4,
    status: "Pending",
    totalAmount: "$2.400.0",
  },
];
